### ISSUE TITLE
Configure Wikifundi refresh with Travis

### ISSUE THREAD

**Issue by kelson42** [openzim/wikifundi#31]
* Run articles updates on time a night
* Run full rebuild on time a week (during the WE)

**Comment by florentk** [comment]
I had write scripts and config for travis, this is here : https://github.com/florentk/wikifundi_management
The script `wikifundi_management.sh` allow to restarting all or specific lang, lauch a partial mirroring and a full mirroring. 
`.travis`  file configure the environnement to start the script with travis, it install sloppy CLI and lauch script. In branch _master_, it not lauch mirroring, but just restart all instance. I add two branch to mirroring : _full_mirroring_ and _partial_mirroring_. 
I can configure a _cron_ but for moment I don't choose a other branch as master ...

**Comment by kelson42** [comment]
@florentk Not understanding everything, but why this is not in the official git repo/wiki? Why you do not simply deal with git master?

**Comment by florentk** [comment]
@kelson42 We can put that in official git, it is just for test because I have not authorized to use the official repository with Travis.
I can't deal with git master only because in cron config in Travis, I don't change env variable, or select a specific travis config file (to specify partial or full mirroring), it use always `.travis ` file in root of repository.

**Comment by florentk** [comment]
@kelson42 actually, the branch is not GIT branch but Travis branch, I understand now ! I can modify .travis file with several branch

**Comment by florentk** [comment]
@kelson42 I had add scripts and config for Travis on official repos, but we must see how config Travis to implement two different mirroring
