### ISSUE TITLE
Modifications recentes not show when edit source with Admin account (bot)

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#71]
http://wikifundi-fr.openzim.org/wiki/Spécial:Modifications_récentes

**Comment by florentk** [comment]
work with visual editor, but not with "edit source", strange !? @kelson42 any idea ?

**Comment by florentk** [comment]
@Anthere @kelson42 
I'am tested, the problem is only for modification with Admin account and source edit. This is because Admin is configured as a Bot (to the mirroring). If you use a other account, all works correctly. You can view bot modification in click on "Afficher les robots"/"Show the bots". This is an issue or not ?

**Comment by Anthere** [comment]
Yes, this is an issue because it deviates significantly with what is "usual" on both wikipedia and vikidia. Admin accounts are not bot accounts. Bots are one thing. Admins are another thing. People will expect (like me) to see modifications by an admin visible. Bot accounts include "bot" in their name (such as "importbot"). This admin account will be used by participants, it needs to be an admin. Not a bot. 
my suggestion: create an "adminbot" or "importbot" and have this one be a "bot". The admin account needs to be an admin account.

**Comment by florentk** [comment]
@Anthere ok I add a specific user for the bot ! Admin will no longer be a bot.
